FROM maven:latest AS MAVEN_BUILD
COPY pom.xml /build/
COPY src /build/src/
WORKDIR /build/
RUN mvn clean package
# CMD ["sleep", "5000"]



FROM adoptopenjdk/openjdk11:armv7l-debianslim-jre11u-nightly
WORKDIR /app
COPY --from=MAVEN_BUILD /build/target/sample-0.0.1-SNAPSHOT.jar /app/
ENTRYPOINT java -XX:+PrintFlagsFinal -jar $JAVA_OPTIONS /app/sample-0.0.1-SNAPSHOT.jar
